package com.jesusdroidl.oppoa79diagnostic;

import android.app.*;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.os.*;import android.os.storage.*;import android.view.*;import android.widget.*;import java.io.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 TextView out; String report="";
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());}
 View ui(){ScrollView s=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(32,40,32,50);r.setBackgroundColor(Color.rgb(9,9,9));s.addView(r);r.addView(t("JESUSDROIDL",14,0xffffd400,true));r.addView(t("OPPO A79 5G DIAGNOSTICO",25,Color.WHITE,true));r.addView(t("Analisis de solo lectura. No elimina ni modifica aplicaciones.",13,0xffcccccc,false));Button a=btn("GENERAR DIAGNOSTICO");a.setOnClickListener(v->scan());r.addView(a);Button sh=btn("COMPARTIR REPORTE TXT");sh.setOnClickListener(v->share());r.addView(sh);out=t("Pulsa GENERAR DIAGNOSTICO.",12,Color.WHITE,false);out.setTypeface(Typeface.MONOSPACE);out.setPadding(20,25,20,25);r.addView(out);return s;}
 TextView t(String x,int z,int c,boolean b){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT_BOLD);return v;} Button btn(String x){Button b=new Button(this);b.setText(x);b.setTypeface(Typeface.DEFAULT_BOLD);b.setTextColor(Color.BLACK);b.setBackgroundColor(0xffffd400);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,18,0,5);b.setLayoutParams(p);return b;}
 void scan(){StringBuilder z=new StringBuilder();z.append("JESUSDROIDL - OPPO A79 5G DIAGNOSTICO\n");z.append("Fecha: ").append(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.getDefault()).format(new Date())).append("\n\n");z.append("=== DISPOSITIVO ===\nFabricante: ").append(Build.MANUFACTURER).append("\nMarca: ").append(Build.BRAND).append("\nModelo: ").append(Build.MODEL).append("\nProducto: ").append(Build.PRODUCT).append("\nDispositivo: ").append(Build.DEVICE).append("\nAndroid: ").append(Build.VERSION.RELEASE).append(" (SDK ").append(Build.VERSION.SDK_INT).append(")\nBuild: ").append(Build.DISPLAY).append("\nParche seguridad: ").append(Build.VERSION.SECURITY_PATCH).append("\n");ActivityManager am=(ActivityManager)getSystemService(ACTIVITY_SERVICE);ActivityManager.MemoryInfo mi=new ActivityManager.MemoryInfo();am.getMemoryInfo(mi);z.append(String.format(Locale.US,"RAM total: %.2f GB\nRAM libre: %.2f GB\n",mi.totalMem/1073741824.0,mi.availMem/1073741824.0));StatFs fs=new StatFs(getFilesDir().getAbsolutePath());z.append(String.format(Locale.US,"Almacenamiento total: %.1f GB\nAlmacenamiento libre: %.1f GB\n",fs.getTotalBytes()/1073741824.0,fs.getAvailableBytes()/1073741824.0));z.append("\n=== APPS VISIBLES / LANZABLES ===\n");PackageManager pm=getPackageManager();Intent q=new Intent(Intent.ACTION_MAIN);q.addCategory(Intent.CATEGORY_LAUNCHER);List<ResolveInfo> rs=pm.queryIntentActivities(q,PackageManager.MATCH_ALL);TreeMap<String,String> apps=new TreeMap<>();for(ResolveInfo ri:rs){try{ApplicationInfo ai=ri.activityInfo.applicationInfo;PackageInfo pi=pm.getPackageInfo(ai.packageName,0);String type=(ai.flags&ApplicationInfo.FLAG_SYSTEM)!=0?"SISTEMA":"USUARIO";String installer="desconocido";try{InstallSourceInfo si=pm.getInstallSourceInfo(ai.packageName);if(si.getInstallingPackageName()!=null)installer=si.getInstallingPackageName();}catch(Exception ignored){}String line=pm.getApplicationLabel(ai)+" | "+ai.packageName+" | v="+pi.versionName+" | "+type+" | enabled="+ai.enabled+" | instalador="+installer;apps.put(ai.packageName,line);}catch(Exception ignored){}}for(String x:apps.values())z.append(x).append("\n");z.append("\nTotal apps visibles: ").append(apps.size()).append("\n\nPRIVACIDAD: no incluye fotos, mensajes, contactos, cuentas, IMEI ni ubicacion.\n");report=z.toString();out.setText(report);}
 void share(){if(report.length()==0){scan();}try{File f=new File(getCacheDir(),"JESUSDROIDL_OPPO_A79_DIAGNOSTICO.txt");try(FileOutputStream o=new FileOutputStream(f)){o.write(report.getBytes("UTF-8"));}Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,report);i.putExtra(Intent.EXTRA_SUBJECT,"JESUSDROIDL OPPO A79 Diagnostico");startActivity(Intent.createChooser(i,"Compartir diagnostico"));}catch(Exception e){Toast.makeText(this,"No se pudo compartir: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
}
